CREATE DATABASE qes4

USE qes4

CREATE TABLE Musician (
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50) NOT NULL,
Ph_Number VARCHAR(20),
City VARCHAR(50),
Street VARCHAR(50)
)

CREATE TABLE Instrument (
Namee VARCHAR(50) PRIMARY KEY,
Keyy VARCHAR(20)
)

CREATE TABLE Album (
Id INT PRIMARY KEY IDENTITY(1,1),
Tittle VARCHAR(100),
Datee DATE,
Mus_Id INT FOREIGN KEY REFERENCES Musician(Id)
)

CREATE TABLE Song (
Tittle VARCHAR(100) PRIMARY KEY,
Author VARCHAR(50)
)

CREATE TABLE Album_song (
Album_Id INT FOREIGN KEY REFERENCES Album(Id),
Song_Title VARCHAR(100) FOREIGN KEY REFERENCES Song(Tittle),
PRIMARY KEY (Album_Id, Song_Title)
)

CREATE TABLE Mus_song (
Mus_Id INT FOREIGN KEY REFERENCES Musician(Id),
Song_Tittle VARCHAR(100) FOREIGN KEY REFERENCES Song(Tittle),
PRIMARY KEY (Mus_Id, Song_Tittle)
)

CREATE TABLE Mus_Instrument (
Mus_Id INT FOREIGN KEY REFERENCES Musician(Id),
Inst_Name VARCHAR(50) FOREIGN KEY REFERENCES Instrument(Namee),
PRIMARY KEY (Mus_Id, Inst_Name)
)
