CREATE DATABASE qes5

USE qes5

CREATE TABLE Sales_Office (
Number INT PRIMARY KEY,
Location VARCHAR(100),
Emp_Id INT
)

CREATE TABLE Employee (
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50),
Off_Number INT FOREIGN KEY REFERENCES Sales_Office(Number)
)

CREATE TABLE Property (
Id INT PRIMARY KEY IDENTITY(1,1),
Address VARCHAR(100),
City VARCHAR(50),
State VARCHAR(50),
Code VARCHAR(10),
Off_Number INT FOREIGN KEY REFERENCES Sales_Office(Number)
)

CREATE TABLE Owner (
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50)
)

CREATE TABLE Prop_Owner (
Own_Id INT FOREIGN KEY REFERENCES Owner(Id),
Prop_Id INT FOREIGN KEY REFERENCES Property(Id),
Precent FLOAT,
PRIMARY KEY (Own_Id, Prop_Id)
)
